### ISSUE TITLE
Add functionality to Snippet button on left menu

### ISSUE THREAD

**Issue by ghackford** [osbornnick/Tuiter#23]
Clicking the Snippet button should take you to the My Snippets screen with a new snippet that you can start entering text into

**Comment by Yanan-G** [comment]
@ghackford What's the difference between this and My Snippets Tab?

**Comment by ghackford** [comment]
The My Snippets tab will display all the existing snippets you have created and saved, while this button is basically what you would click on to create a new snippet. In other words, the My Snippets tab shows a list of your snippets and the snippet button allows you to create a new one that will then be stored and shown in the My Snippets screen.
