### ISSUE TITLE
Add Share button to Snippets

### ISSUE THREAD

**Issue by ghackford** [osbornnick/Tuiter#24]
Share button can either take you back to the home screen to enter a new Tuit while retaining the reference to the snippet, or it can pop up a text window for the user to enter the tuit text in

**Comment by Yanan-G** [comment]
@ghackford So this button would give the user two options, like a drop-down menu?  And it should display on the My Snippets screen, correct?

**Comment by ghackford** [comment]
We weren't totally sure how we wanted to do this. Basically to share the snippet, you have to create a Tuit. The button should appear under the snippet, like the Run and Save buttons currently do, and could either 1) pop up a dialogue box so that you can enter text for the Tuit or 2) direct you to the home screen to enter a new Tuit. I think it's up to you which you think would work better.
